name: monadic-social
version: 0.1.0.0
github: "Varsha-Jaiswal/MonadicSocial"
license: BSD-3-Clause
author: "Varsha Jaiswal"
maintainer: "v.jaiswal@se25.qmul.ac.uk"
copyright: "2026 Varsha Jaiswal"

extra-source-files:
  - README.md

dependencies:
  - base >= 4.7 && < 5
  - containers
  - stm
  - time
  - mtl

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src
  exposed-modules:
    - Types
    - Config
    - Env
    - Logger
    - Capabilities
    - Run

executables:
  monadic-social-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - monadic-social
